on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Testes"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # roda no push para main OU quando o workflow Testes terminar com sucesso
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success')
    env:
      VERCEL_TOKEN:       ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID:      ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID:  ${{ secrets.VERCEL_PROJECT_ID }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Instalar pacotes UI específicos
        run: npm install --legacy-peer-deps react-day-picker date-fns @radix-ui/react-popover clsx

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          npm install -g npm@latest
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --force

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
